coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 2%
    patch:
      default:
        target: 80%

ignore:
  - "cmd/**"
  - "examples/**"
  - "pkg/proto/**"
  - "**/*.pb.go"
