// Code generated by protoc-gen-go. DO NOT EDIT.
// source: util/completeTx.proto

package protocol_util

import (
	api "api"
	core "core"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProtoCompleteTransaction struct {
	BlockNumber          uint64                    `protobuf:"varint,1,opt,name=BlockNumber,proto3" json:"BlockNumber,omitempty"`
	BlockTime            uint64                    `protobuf:"varint,2,opt,name=BlockTime,proto3" json:"BlockTime,omitempty"`
	Tx                   *api.TransactionExtention `protobuf:"bytes,3,opt,name=Tx,proto3" json:"Tx,omitempty"`
	Info                 *core.TransactionInfo     `protobuf:"bytes,4,opt,name=Info,proto3" json:"Info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ProtoCompleteTransaction) Reset()         { *m = ProtoCompleteTransaction{} }
func (m *ProtoCompleteTransaction) String() string { return proto.CompactTextString(m) }
func (*ProtoCompleteTransaction) ProtoMessage()    {}
func (*ProtoCompleteTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad72d1b67bea25c6, []int{0}
}

func (m *ProtoCompleteTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoCompleteTransaction.Unmarshal(m, b)
}
func (m *ProtoCompleteTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoCompleteTransaction.Marshal(b, m, deterministic)
}
func (m *ProtoCompleteTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoCompleteTransaction.Merge(m, src)
}
func (m *ProtoCompleteTransaction) XXX_Size() int {
	return xxx_messageInfo_ProtoCompleteTransaction.Size(m)
}
func (m *ProtoCompleteTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoCompleteTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoCompleteTransaction proto.InternalMessageInfo

func (m *ProtoCompleteTransaction) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

func (m *ProtoCompleteTransaction) GetBlockTime() uint64 {
	if m != nil {
		return m.BlockTime
	}
	return 0
}

func (m *ProtoCompleteTransaction) GetTx() *api.TransactionExtention {
	if m != nil {
		return m.Tx
	}
	return nil
}

func (m *ProtoCompleteTransaction) GetInfo() *core.TransactionInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func init() {
	proto.RegisterType((*ProtoCompleteTransaction)(nil), "protocol.util.ProtoCompleteTransaction")
}

func init() { proto.RegisterFile("util/completeTx.proto", fileDescriptor_ad72d1b67bea25c6) }

var fileDescriptor_ad72d1b67bea25c6 = []byte{
	// 197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x2d, 0xc9, 0xcc,
	0xd1, 0x4f, 0xce, 0xcf, 0x2d, 0xc8, 0x49, 0x2d, 0x49, 0x0d, 0xa9, 0xd0, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0xe2, 0x05, 0x53, 0xc9, 0xf9, 0x39, 0x7a, 0x20, 0x79, 0x29, 0x31, 0x18, 0x57, 0x3f,
	0xb1, 0x20, 0x13, 0x84, 0x21, 0xca, 0xa4, 0xf8, 0x93, 0xf3, 0x8b, 0x52, 0xf5, 0x43, 0x8a, 0xf2,
	0xf3, 0x20, 0x02, 0x4a, 0x3b, 0x19, 0xb9, 0x24, 0x02, 0x40, 0x2c, 0x67, 0x98, 0x89, 0x45, 0x89,
	0x79, 0xc5, 0x89, 0xc9, 0x25, 0x99, 0xf9, 0x79, 0x42, 0x0a, 0x5c, 0xdc, 0x4e, 0x39, 0xf9, 0xc9,
	0xd9, 0x7e, 0xa5, 0xb9, 0x49, 0xa9, 0x45, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x2c, 0x41, 0xc8, 0x42,
	0x42, 0x32, 0x5c, 0x9c, 0x60, 0x6e, 0x48, 0x66, 0x6e, 0xaa, 0x04, 0x13, 0x58, 0x1e, 0x21, 0x20,
	0xa4, 0xc7, 0xc5, 0x14, 0x52, 0x21, 0xc1, 0xac, 0xc0, 0xa8, 0xc1, 0x6d, 0x24, 0xa7, 0x07, 0x77,
	0x21, 0x92, 0x15, 0xae, 0x15, 0x25, 0xa9, 0x79, 0x20, 0x46, 0x10, 0x53, 0x48, 0x85, 0x90, 0x2e,
	0x17, 0x8b, 0x67, 0x5e, 0x5a, 0xbe, 0x04, 0x0b, 0x58, 0x87, 0x24, 0x56, 0x1d, 0x20, 0x05, 0x41,
	0x60, 0x65, 0x49, 0x6c, 0x60, 0x79, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7c, 0xcb, 0xb7,
	0x14, 0x13, 0x01, 0x00, 0x00,
}
