// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: completeTx.proto

package util

import (
	api "github.com/fbsobreira/gotron-sdk/pkg/proto/api"
	core "github.com/fbsobreira/gotron-sdk/pkg/proto/core"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtoCompleteTransaction struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	BlockNumber   uint64                    `protobuf:"varint,1,opt,name=BlockNumber,proto3" json:"BlockNumber,omitempty"`
	BlockTime     uint64                    `protobuf:"varint,2,opt,name=BlockTime,proto3" json:"BlockTime,omitempty"`
	Tx            *api.TransactionExtention `protobuf:"bytes,3,opt,name=Tx,proto3" json:"Tx,omitempty"`
	Info          *core.TransactionInfo     `protobuf:"bytes,4,opt,name=Info,proto3" json:"Info,omitempty"`
	ExchangeInfo  *core.Exchange            `protobuf:"bytes,5,opt,name=ExchangeInfo,proto3" json:"ExchangeInfo,omitempty"`
	AssetInfo     *core.AssetIssueContract  `protobuf:"bytes,6,opt,name=AssetInfo,proto3" json:"AssetInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoCompleteTransaction) Reset() {
	*x = ProtoCompleteTransaction{}
	mi := &file_completeTx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoCompleteTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoCompleteTransaction) ProtoMessage() {}

func (x *ProtoCompleteTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_completeTx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoCompleteTransaction.ProtoReflect.Descriptor instead.
func (*ProtoCompleteTransaction) Descriptor() ([]byte, []int) {
	return file_completeTx_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoCompleteTransaction) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *ProtoCompleteTransaction) GetBlockTime() uint64 {
	if x != nil {
		return x.BlockTime
	}
	return 0
}

func (x *ProtoCompleteTransaction) GetTx() *api.TransactionExtention {
	if x != nil {
		return x.Tx
	}
	return nil
}

func (x *ProtoCompleteTransaction) GetInfo() *core.TransactionInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *ProtoCompleteTransaction) GetExchangeInfo() *core.Exchange {
	if x != nil {
		return x.ExchangeInfo
	}
	return nil
}

func (x *ProtoCompleteTransaction) GetAssetInfo() *core.AssetIssueContract {
	if x != nil {
		return x.AssetInfo
	}
	return nil
}

var File_completeTx_proto protoreflect.FileDescriptor

const file_completeTx_proto_rawDesc = "" +
	"\n" +
	"\x10completeTx.proto\x12\bprotocol\x1a\x0fcore/Tron.proto\x1a\rapi/api.proto\x1a(core/contract/asset_issue_contract.proto\"\xad\x02\n" +
	"\x18ProtoCompleteTransaction\x12 \n" +
	"\vBlockNumber\x18\x01 \x01(\x04R\vBlockNumber\x12\x1c\n" +
	"\tBlockTime\x18\x02 \x01(\x04R\tBlockTime\x12.\n" +
	"\x02Tx\x18\x03 \x01(\v2\x1e.protocol.TransactionExtentionR\x02Tx\x12-\n" +
	"\x04Info\x18\x04 \x01(\v2\x19.protocol.TransactionInfoR\x04Info\x126\n" +
	"\fExchangeInfo\x18\x05 \x01(\v2\x12.protocol.ExchangeR\fExchangeInfo\x12:\n" +
	"\tAssetInfo\x18\x06 \x01(\v2\x1c.protocol.AssetIssueContractR\tAssetInfoB1Z/github.com/fbsobreira/gotron-sdk/pkg/proto/utilb\x06proto3"

var (
	file_completeTx_proto_rawDescOnce sync.Once
	file_completeTx_proto_rawDescData []byte
)

func file_completeTx_proto_rawDescGZIP() []byte {
	file_completeTx_proto_rawDescOnce.Do(func() {
		file_completeTx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_completeTx_proto_rawDesc), len(file_completeTx_proto_rawDesc)))
	})
	return file_completeTx_proto_rawDescData
}

var file_completeTx_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_completeTx_proto_goTypes = []any{
	(*ProtoCompleteTransaction)(nil), // 0: protocol.ProtoCompleteTransaction
	(*api.TransactionExtention)(nil), // 1: protocol.TransactionExtention
	(*core.TransactionInfo)(nil),     // 2: protocol.TransactionInfo
	(*core.Exchange)(nil),            // 3: protocol.Exchange
	(*core.AssetIssueContract)(nil),  // 4: protocol.AssetIssueContract
}
var file_completeTx_proto_depIdxs = []int32{
	1, // 0: protocol.ProtoCompleteTransaction.Tx:type_name -> protocol.TransactionExtention
	2, // 1: protocol.ProtoCompleteTransaction.Info:type_name -> protocol.TransactionInfo
	3, // 2: protocol.ProtoCompleteTransaction.ExchangeInfo:type_name -> protocol.Exchange
	4, // 3: protocol.ProtoCompleteTransaction.AssetInfo:type_name -> protocol.AssetIssueContract
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_completeTx_proto_init() }
func file_completeTx_proto_init() {
	if File_completeTx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_completeTx_proto_rawDesc), len(file_completeTx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_completeTx_proto_goTypes,
		DependencyIndexes: file_completeTx_proto_depIdxs,
		MessageInfos:      file_completeTx_proto_msgTypes,
	}.Build()
	File_completeTx_proto = out.File
	file_completeTx_proto_goTypes = nil
	file_completeTx_proto_depIdxs = nil
}
