// Code generated by protoc-gen-go. DO NOT EDIT.
// source: core/Contract.proto

/*
Package core is a generated protocol buffer package.

It is generated from these files:
	core/Contract.proto
	core/Discover.proto
	core/Tron.proto
	core/TronInventoryItems.proto

It has these top-level messages:
	AccountCreateContract
	AccountUpdateContract
	TransferContract
	TransferAssetContract
	VoteAssetContract
	VoteWitnessContract
	WitnessCreateContract
	WitnessUpdateContract
	AssetIssueContract
	ParticipateAssetIssueContract
	DeployContract
	FreezeBalanceContract
	UnfreezeBalanceContract
	UnfreezeAssetContract
	WithdrawBalanceContract
	UpdateAssetContract
	Endpoint
	PingMessage
	PongMessage
	FindNeighbours
	Neighbours
	AccountId
	Vote
	Account
	Acuthrity
	Permision
	Witness
	Votes
	TXOutput
	TXInput
	TXOutputs
	Transaction
	Transactions
	BlockHeader
	Block
	ChainInventory
	BlockInventory
	Inventory
	Items
	DynamicProperties
	DisconnectMessage
	HelloMessage
	InventoryItems
*/
package core

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AccountCreateContract struct {
	OwnerAddress   []byte      `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	AccountAddress []byte      `protobuf:"bytes,2,opt,name=account_address,json=accountAddress,proto3" json:"account_address,omitempty"`
	Type           AccountType `protobuf:"varint,3,opt,name=type,enum=protocol.AccountType" json:"type,omitempty"`
}

func (m *AccountCreateContract) Reset()                    { *m = AccountCreateContract{} }
func (m *AccountCreateContract) String() string            { return proto.CompactTextString(m) }
func (*AccountCreateContract) ProtoMessage()               {}
func (*AccountCreateContract) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AccountCreateContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *AccountCreateContract) GetAccountAddress() []byte {
	if m != nil {
		return m.AccountAddress
	}
	return nil
}

func (m *AccountCreateContract) GetType() AccountType {
	if m != nil {
		return m.Type
	}
	return AccountType_Normal
}

// update account name if the account has no name.
type AccountUpdateContract struct {
	AccountName  []byte `protobuf:"bytes,1,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	OwnerAddress []byte `protobuf:"bytes,2,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
}

func (m *AccountUpdateContract) Reset()                    { *m = AccountUpdateContract{} }
func (m *AccountUpdateContract) String() string            { return proto.CompactTextString(m) }
func (*AccountUpdateContract) ProtoMessage()               {}
func (*AccountUpdateContract) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AccountUpdateContract) GetAccountName() []byte {
	if m != nil {
		return m.AccountName
	}
	return nil
}

func (m *AccountUpdateContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

type TransferContract struct {
	OwnerAddress []byte `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	ToAddress    []byte `protobuf:"bytes,2,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	Amount       int64  `protobuf:"varint,3,opt,name=amount" json:"amount,omitempty"`
}

func (m *TransferContract) Reset()                    { *m = TransferContract{} }
func (m *TransferContract) String() string            { return proto.CompactTextString(m) }
func (*TransferContract) ProtoMessage()               {}
func (*TransferContract) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TransferContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *TransferContract) GetToAddress() []byte {
	if m != nil {
		return m.ToAddress
	}
	return nil
}

func (m *TransferContract) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type TransferAssetContract struct {
	AssetName    []byte `protobuf:"bytes,1,opt,name=asset_name,json=assetName,proto3" json:"asset_name,omitempty"`
	OwnerAddress []byte `protobuf:"bytes,2,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	ToAddress    []byte `protobuf:"bytes,3,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	Amount       int64  `protobuf:"varint,4,opt,name=amount" json:"amount,omitempty"`
}

func (m *TransferAssetContract) Reset()                    { *m = TransferAssetContract{} }
func (m *TransferAssetContract) String() string            { return proto.CompactTextString(m) }
func (*TransferAssetContract) ProtoMessage()               {}
func (*TransferAssetContract) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TransferAssetContract) GetAssetName() []byte {
	if m != nil {
		return m.AssetName
	}
	return nil
}

func (m *TransferAssetContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *TransferAssetContract) GetToAddress() []byte {
	if m != nil {
		return m.ToAddress
	}
	return nil
}

func (m *TransferAssetContract) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type VoteAssetContract struct {
	OwnerAddress []byte   `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	VoteAddress  [][]byte `protobuf:"bytes,2,rep,name=vote_address,json=voteAddress,proto3" json:"vote_address,omitempty"`
	Support      bool     `protobuf:"varint,3,opt,name=support" json:"support,omitempty"`
	Count        int32    `protobuf:"varint,5,opt,name=count" json:"count,omitempty"`
}

func (m *VoteAssetContract) Reset()                    { *m = VoteAssetContract{} }
func (m *VoteAssetContract) String() string            { return proto.CompactTextString(m) }
func (*VoteAssetContract) ProtoMessage()               {}
func (*VoteAssetContract) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *VoteAssetContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *VoteAssetContract) GetVoteAddress() [][]byte {
	if m != nil {
		return m.VoteAddress
	}
	return nil
}

func (m *VoteAssetContract) GetSupport() bool {
	if m != nil {
		return m.Support
	}
	return false
}

func (m *VoteAssetContract) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type VoteWitnessContract struct {
	OwnerAddress []byte                      `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	Votes        []*VoteWitnessContract_Vote `protobuf:"bytes,2,rep,name=votes" json:"votes,omitempty"`
	Support      bool                        `protobuf:"varint,3,opt,name=support" json:"support,omitempty"`
}

func (m *VoteWitnessContract) Reset()                    { *m = VoteWitnessContract{} }
func (m *VoteWitnessContract) String() string            { return proto.CompactTextString(m) }
func (*VoteWitnessContract) ProtoMessage()               {}
func (*VoteWitnessContract) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *VoteWitnessContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *VoteWitnessContract) GetVotes() []*VoteWitnessContract_Vote {
	if m != nil {
		return m.Votes
	}
	return nil
}

func (m *VoteWitnessContract) GetSupport() bool {
	if m != nil {
		return m.Support
	}
	return false
}

type VoteWitnessContract_Vote struct {
	VoteAddress []byte `protobuf:"bytes,1,opt,name=vote_address,json=voteAddress,proto3" json:"vote_address,omitempty"`
	VoteCount   int64  `protobuf:"varint,2,opt,name=vote_count,json=voteCount" json:"vote_count,omitempty"`
}

func (m *VoteWitnessContract_Vote) Reset()                    { *m = VoteWitnessContract_Vote{} }
func (m *VoteWitnessContract_Vote) String() string            { return proto.CompactTextString(m) }
func (*VoteWitnessContract_Vote) ProtoMessage()               {}
func (*VoteWitnessContract_Vote) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 0} }

func (m *VoteWitnessContract_Vote) GetVoteAddress() []byte {
	if m != nil {
		return m.VoteAddress
	}
	return nil
}

func (m *VoteWitnessContract_Vote) GetVoteCount() int64 {
	if m != nil {
		return m.VoteCount
	}
	return 0
}

type WitnessCreateContract struct {
	OwnerAddress []byte `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	Url          []byte `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
}

func (m *WitnessCreateContract) Reset()                    { *m = WitnessCreateContract{} }
func (m *WitnessCreateContract) String() string            { return proto.CompactTextString(m) }
func (*WitnessCreateContract) ProtoMessage()               {}
func (*WitnessCreateContract) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *WitnessCreateContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *WitnessCreateContract) GetUrl() []byte {
	if m != nil {
		return m.Url
	}
	return nil
}

type WitnessUpdateContract struct {
	OwnerAddress []byte `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	UpdateUrl    []byte `protobuf:"bytes,12,opt,name=update_url,json=updateUrl,proto3" json:"update_url,omitempty"`
}

func (m *WitnessUpdateContract) Reset()                    { *m = WitnessUpdateContract{} }
func (m *WitnessUpdateContract) String() string            { return proto.CompactTextString(m) }
func (*WitnessUpdateContract) ProtoMessage()               {}
func (*WitnessUpdateContract) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *WitnessUpdateContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *WitnessUpdateContract) GetUpdateUrl() []byte {
	if m != nil {
		return m.UpdateUrl
	}
	return nil
}

type AssetIssueContract struct {
	OwnerAddress            []byte                             `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	Name                    []byte                             `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Abbr                    []byte                             `protobuf:"bytes,3,opt,name=abbr,proto3" json:"abbr,omitempty"`
	TotalSupply             int64                              `protobuf:"varint,4,opt,name=total_supply,json=totalSupply" json:"total_supply,omitempty"`
	FrozenSupply            []*AssetIssueContract_FrozenSupply `protobuf:"bytes,5,rep,name=frozen_supply,json=frozenSupply" json:"frozen_supply,omitempty"`
	TrxNum                  int32                              `protobuf:"varint,6,opt,name=trx_num,json=trxNum" json:"trx_num,omitempty"`
	Num                     int32                              `protobuf:"varint,8,opt,name=num" json:"num,omitempty"`
	StartTime               int64                              `protobuf:"varint,9,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	EndTime                 int64                              `protobuf:"varint,10,opt,name=end_time,json=endTime" json:"end_time,omitempty"`
	VoteScore               int32                              `protobuf:"varint,16,opt,name=vote_score,json=voteScore" json:"vote_score,omitempty"`
	Description             []byte                             `protobuf:"bytes,20,opt,name=description,proto3" json:"description,omitempty"`
	Url                     []byte                             `protobuf:"bytes,21,opt,name=url,proto3" json:"url,omitempty"`
	FreeAssetNetLimit       int64                              `protobuf:"varint,22,opt,name=free_asset_net_limit,json=freeAssetNetLimit" json:"free_asset_net_limit,omitempty"`
	PublicFreeAssetNetLimit int64                              `protobuf:"varint,23,opt,name=public_free_asset_net_limit,json=publicFreeAssetNetLimit" json:"public_free_asset_net_limit,omitempty"`
	PublicFreeAssetNetUsage int64                              `protobuf:"varint,24,opt,name=public_free_asset_net_usage,json=publicFreeAssetNetUsage" json:"public_free_asset_net_usage,omitempty"`
	PublicLatestFreeNetTime int64                              `protobuf:"varint,25,opt,name=public_latest_free_net_time,json=publicLatestFreeNetTime" json:"public_latest_free_net_time,omitempty"`
}

func (m *AssetIssueContract) Reset()                    { *m = AssetIssueContract{} }
func (m *AssetIssueContract) String() string            { return proto.CompactTextString(m) }
func (*AssetIssueContract) ProtoMessage()               {}
func (*AssetIssueContract) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *AssetIssueContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *AssetIssueContract) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *AssetIssueContract) GetAbbr() []byte {
	if m != nil {
		return m.Abbr
	}
	return nil
}

func (m *AssetIssueContract) GetTotalSupply() int64 {
	if m != nil {
		return m.TotalSupply
	}
	return 0
}

func (m *AssetIssueContract) GetFrozenSupply() []*AssetIssueContract_FrozenSupply {
	if m != nil {
		return m.FrozenSupply
	}
	return nil
}

func (m *AssetIssueContract) GetTrxNum() int32 {
	if m != nil {
		return m.TrxNum
	}
	return 0
}

func (m *AssetIssueContract) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *AssetIssueContract) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *AssetIssueContract) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *AssetIssueContract) GetVoteScore() int32 {
	if m != nil {
		return m.VoteScore
	}
	return 0
}

func (m *AssetIssueContract) GetDescription() []byte {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *AssetIssueContract) GetUrl() []byte {
	if m != nil {
		return m.Url
	}
	return nil
}

func (m *AssetIssueContract) GetFreeAssetNetLimit() int64 {
	if m != nil {
		return m.FreeAssetNetLimit
	}
	return 0
}

func (m *AssetIssueContract) GetPublicFreeAssetNetLimit() int64 {
	if m != nil {
		return m.PublicFreeAssetNetLimit
	}
	return 0
}

func (m *AssetIssueContract) GetPublicFreeAssetNetUsage() int64 {
	if m != nil {
		return m.PublicFreeAssetNetUsage
	}
	return 0
}

func (m *AssetIssueContract) GetPublicLatestFreeNetTime() int64 {
	if m != nil {
		return m.PublicLatestFreeNetTime
	}
	return 0
}

type AssetIssueContract_FrozenSupply struct {
	FrozenAmount int64 `protobuf:"varint,1,opt,name=frozen_amount,json=frozenAmount" json:"frozen_amount,omitempty"`
	FrozenDays   int64 `protobuf:"varint,2,opt,name=frozen_days,json=frozenDays" json:"frozen_days,omitempty"`
}

func (m *AssetIssueContract_FrozenSupply) Reset()         { *m = AssetIssueContract_FrozenSupply{} }
func (m *AssetIssueContract_FrozenSupply) String() string { return proto.CompactTextString(m) }
func (*AssetIssueContract_FrozenSupply) ProtoMessage()    {}
func (*AssetIssueContract_FrozenSupply) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{8, 0}
}

func (m *AssetIssueContract_FrozenSupply) GetFrozenAmount() int64 {
	if m != nil {
		return m.FrozenAmount
	}
	return 0
}

func (m *AssetIssueContract_FrozenSupply) GetFrozenDays() int64 {
	if m != nil {
		return m.FrozenDays
	}
	return 0
}

type ParticipateAssetIssueContract struct {
	OwnerAddress []byte `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	ToAddress    []byte `protobuf:"bytes,2,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	AssetName    []byte `protobuf:"bytes,3,opt,name=asset_name,json=assetName,proto3" json:"asset_name,omitempty"`
	Amount       int64  `protobuf:"varint,4,opt,name=amount" json:"amount,omitempty"`
}

func (m *ParticipateAssetIssueContract) Reset()                    { *m = ParticipateAssetIssueContract{} }
func (m *ParticipateAssetIssueContract) String() string            { return proto.CompactTextString(m) }
func (*ParticipateAssetIssueContract) ProtoMessage()               {}
func (*ParticipateAssetIssueContract) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ParticipateAssetIssueContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *ParticipateAssetIssueContract) GetToAddress() []byte {
	if m != nil {
		return m.ToAddress
	}
	return nil
}

func (m *ParticipateAssetIssueContract) GetAssetName() []byte {
	if m != nil {
		return m.AssetName
	}
	return nil
}

func (m *ParticipateAssetIssueContract) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type DeployContract struct {
	OwnerAddress []byte `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	Script       []byte `protobuf:"bytes,2,opt,name=script,proto3" json:"script,omitempty"`
}

func (m *DeployContract) Reset()                    { *m = DeployContract{} }
func (m *DeployContract) String() string            { return proto.CompactTextString(m) }
func (*DeployContract) ProtoMessage()               {}
func (*DeployContract) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *DeployContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *DeployContract) GetScript() []byte {
	if m != nil {
		return m.Script
	}
	return nil
}

type FreezeBalanceContract struct {
	OwnerAddress   []byte `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	FrozenBalance  int64  `protobuf:"varint,2,opt,name=frozen_balance,json=frozenBalance" json:"frozen_balance,omitempty"`
	FrozenDuration int64  `protobuf:"varint,3,opt,name=frozen_duration,json=frozenDuration" json:"frozen_duration,omitempty"`
}

func (m *FreezeBalanceContract) Reset()                    { *m = FreezeBalanceContract{} }
func (m *FreezeBalanceContract) String() string            { return proto.CompactTextString(m) }
func (*FreezeBalanceContract) ProtoMessage()               {}
func (*FreezeBalanceContract) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *FreezeBalanceContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *FreezeBalanceContract) GetFrozenBalance() int64 {
	if m != nil {
		return m.FrozenBalance
	}
	return 0
}

func (m *FreezeBalanceContract) GetFrozenDuration() int64 {
	if m != nil {
		return m.FrozenDuration
	}
	return 0
}

type UnfreezeBalanceContract struct {
	OwnerAddress []byte `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
}

func (m *UnfreezeBalanceContract) Reset()                    { *m = UnfreezeBalanceContract{} }
func (m *UnfreezeBalanceContract) String() string            { return proto.CompactTextString(m) }
func (*UnfreezeBalanceContract) ProtoMessage()               {}
func (*UnfreezeBalanceContract) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *UnfreezeBalanceContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

type UnfreezeAssetContract struct {
	OwnerAddress []byte `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
}

func (m *UnfreezeAssetContract) Reset()                    { *m = UnfreezeAssetContract{} }
func (m *UnfreezeAssetContract) String() string            { return proto.CompactTextString(m) }
func (*UnfreezeAssetContract) ProtoMessage()               {}
func (*UnfreezeAssetContract) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *UnfreezeAssetContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

type WithdrawBalanceContract struct {
	OwnerAddress []byte `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
}

func (m *WithdrawBalanceContract) Reset()                    { *m = WithdrawBalanceContract{} }
func (m *WithdrawBalanceContract) String() string            { return proto.CompactTextString(m) }
func (*WithdrawBalanceContract) ProtoMessage()               {}
func (*WithdrawBalanceContract) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *WithdrawBalanceContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

type UpdateAssetContract struct {
	OwnerAddress   []byte `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	Description    []byte `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Url            []byte `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	NewLimit       int64  `protobuf:"varint,4,opt,name=new_limit,json=newLimit" json:"new_limit,omitempty"`
	NewPublicLimit int64  `protobuf:"varint,5,opt,name=new_public_limit,json=newPublicLimit" json:"new_public_limit,omitempty"`
}

func (m *UpdateAssetContract) Reset()                    { *m = UpdateAssetContract{} }
func (m *UpdateAssetContract) String() string            { return proto.CompactTextString(m) }
func (*UpdateAssetContract) ProtoMessage()               {}
func (*UpdateAssetContract) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *UpdateAssetContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *UpdateAssetContract) GetDescription() []byte {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *UpdateAssetContract) GetUrl() []byte {
	if m != nil {
		return m.Url
	}
	return nil
}

func (m *UpdateAssetContract) GetNewLimit() int64 {
	if m != nil {
		return m.NewLimit
	}
	return 0
}

func (m *UpdateAssetContract) GetNewPublicLimit() int64 {
	if m != nil {
		return m.NewPublicLimit
	}
	return 0
}

func init() {
	proto.RegisterType((*AccountCreateContract)(nil), "protocol.AccountCreateContract")
	proto.RegisterType((*AccountUpdateContract)(nil), "protocol.AccountUpdateContract")
	proto.RegisterType((*TransferContract)(nil), "protocol.TransferContract")
	proto.RegisterType((*TransferAssetContract)(nil), "protocol.TransferAssetContract")
	proto.RegisterType((*VoteAssetContract)(nil), "protocol.VoteAssetContract")
	proto.RegisterType((*VoteWitnessContract)(nil), "protocol.VoteWitnessContract")
	proto.RegisterType((*VoteWitnessContract_Vote)(nil), "protocol.VoteWitnessContract.Vote")
	proto.RegisterType((*WitnessCreateContract)(nil), "protocol.WitnessCreateContract")
	proto.RegisterType((*WitnessUpdateContract)(nil), "protocol.WitnessUpdateContract")
	proto.RegisterType((*AssetIssueContract)(nil), "protocol.AssetIssueContract")
	proto.RegisterType((*AssetIssueContract_FrozenSupply)(nil), "protocol.AssetIssueContract.FrozenSupply")
	proto.RegisterType((*ParticipateAssetIssueContract)(nil), "protocol.ParticipateAssetIssueContract")
	proto.RegisterType((*DeployContract)(nil), "protocol.DeployContract")
	proto.RegisterType((*FreezeBalanceContract)(nil), "protocol.FreezeBalanceContract")
	proto.RegisterType((*UnfreezeBalanceContract)(nil), "protocol.UnfreezeBalanceContract")
	proto.RegisterType((*UnfreezeAssetContract)(nil), "protocol.UnfreezeAssetContract")
	proto.RegisterType((*WithdrawBalanceContract)(nil), "protocol.WithdrawBalanceContract")
	proto.RegisterType((*UpdateAssetContract)(nil), "protocol.UpdateAssetContract")
}

func init() { proto.RegisterFile("core/Contract.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 928 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x06, 0x2d, 0x4b, 0x96, 0x46, 0x8a, 0xed, 0xd0, 0x96, 0xcd, 0x38, 0x30, 0xea, 0xb0, 0x08,
	0xea, 0x1c, 0x22, 0x01, 0xe9, 0xa5, 0x87, 0xa0, 0x80, 0x7f, 0x10, 0xb4, 0x40, 0x2a, 0x04, 0x8a,
	0xdc, 0x00, 0xed, 0x41, 0x58, 0x51, 0x23, 0x87, 0x00, 0xb9, 0x4b, 0xec, 0x2e, 0x2b, 0x2b, 0xaf,
	0xd0, 0x1e, 0x8a, 0x1e, 0xfb, 0x1e, 0x7d, 0x8c, 0xde, 0xfb, 0x38, 0xc5, 0xce, 0x2e, 0x15, 0x5a,
	0xb6, 0x10, 0x4b, 0x27, 0x91, 0xdf, 0xfc, 0xec, 0xb7, 0x33, 0xdf, 0x0c, 0x05, 0x7b, 0x91, 0x90,
	0xd8, 0xbd, 0x10, 0x5c, 0x4b, 0x16, 0xe9, 0x4e, 0x26, 0x85, 0x16, 0x7e, 0x9d, 0x7e, 0x22, 0x91,
	0x1c, 0xed, 0x90, 0x79, 0x20, 0x05, 0xb7, 0xa6, 0xf0, 0x4f, 0x0f, 0xda, 0x67, 0x51, 0x24, 0x72,
	0xae, 0x2f, 0x24, 0x32, 0x8d, 0x45, 0xa8, 0xff, 0x35, 0x3c, 0x12, 0x53, 0x8e, 0x72, 0xc8, 0xc6,
	0x63, 0x89, 0x4a, 0x05, 0xde, 0x89, 0x77, 0xda, 0xea, 0xb7, 0x08, 0x3c, 0xb3, 0x98, 0xff, 0x0d,
	0xec, 0x30, 0x1b, 0x3d, 0x77, 0xdb, 0x20, 0xb7, 0x6d, 0x07, 0x17, 0x8e, 0x2f, 0x60, 0x53, 0xcf,
	0x32, 0x0c, 0x2a, 0x27, 0xde, 0xe9, 0xf6, 0xab, 0x76, 0xa7, 0x60, 0xd4, 0x71, 0x87, 0x0f, 0x66,
	0x19, 0xf6, 0xc9, 0x25, 0x1c, 0xce, 0x19, 0x5d, 0x65, 0xe3, 0x32, 0xa3, 0x67, 0xd0, 0x2a, 0x0e,
	0xe3, 0x2c, 0x45, 0x47, 0xa8, 0xe9, 0xb0, 0x1e, 0x4b, 0xf1, 0x2e, 0xe9, 0x8d, 0xbb, 0xa4, 0x43,
	0x0e, 0xbb, 0x03, 0xc9, 0xb8, 0x9a, 0xa0, 0x5c, 0xed, 0xb6, 0xc7, 0x00, 0x5a, 0x2c, 0xa4, 0x6e,
	0x68, 0x51, 0x98, 0x0f, 0xa0, 0xc6, 0x52, 0x43, 0x85, 0x6e, 0x59, 0xe9, 0xbb, 0xb7, 0xf0, 0x2f,
	0x0f, 0xda, 0xc5, 0x81, 0x67, 0x4a, 0xa1, 0x9e, 0x9f, 0x7a, 0x0c, 0xc0, 0x0c, 0x50, 0xbe, 0x4f,
	0x83, 0x90, 0x07, 0xdf, 0x66, 0x81, 0x54, 0x65, 0x39, 0xa9, 0xcd, 0x5b, 0xa4, 0x7e, 0xf7, 0xe0,
	0xf1, 0xcf, 0x42, 0xe3, 0x6d, 0x42, 0x0f, 0x2a, 0xc3, 0x33, 0x68, 0xfd, 0x26, 0x34, 0x96, 0x58,
	0x55, 0x4c, 0x1f, 0x0c, 0x56, 0xb8, 0x04, 0xb0, 0xa5, 0xf2, 0x2c, 0x13, 0xd2, 0xd6, 0xa2, 0xde,
	0x2f, 0x5e, 0xfd, 0x7d, 0xa8, 0x52, 0xbb, 0x82, 0xea, 0x89, 0x77, 0x5a, 0xed, 0xdb, 0x97, 0xf0,
	0x3f, 0x0f, 0xf6, 0x0c, 0x9b, 0x0f, 0xb1, 0xe6, 0xa8, 0xd4, 0x6a, 0x7c, 0xbe, 0x83, 0xaa, 0x39,
	0xdb, 0x12, 0x69, 0xbe, 0x0a, 0x3f, 0x8b, 0xeb, 0x9e, 0x94, 0x84, 0xf5, 0x6d, 0xc0, 0x72, 0x9a,
	0x47, 0x3f, 0xc0, 0xa6, 0x71, 0xbc, 0x73, 0x57, 0xa7, 0xb9, 0xf2, 0x5d, 0x8f, 0x01, 0xc8, 0xc5,
	0x5e, 0x6b, 0x83, 0xaa, 0xdc, 0x30, 0xc8, 0x05, 0x5d, 0xad, 0x07, 0xed, 0x82, 0xc2, 0x1a, 0x03,
	0xb6, 0x0b, 0x95, 0x5c, 0x26, 0xae, 0xf1, 0xe6, 0x31, 0xfc, 0x75, 0x9e, 0x6f, 0x61, 0x3c, 0x1e,
	0x2a, 0xe1, 0x9c, 0xc2, 0x86, 0x26, 0x6d, 0xcb, 0xaa, 0xc5, 0x22, 0x57, 0x32, 0x09, 0xff, 0xad,
	0x82, 0x4f, 0x8a, 0xf8, 0x51, 0xa9, 0x7c, 0xc5, 0xd4, 0x3e, 0x6c, 0x92, 0x8c, 0x2d, 0x57, 0x7a,
	0x36, 0x18, 0x1b, 0x8d, 0xa4, 0x93, 0x25, 0x3d, 0x9b, 0x92, 0x6a, 0xa1, 0x59, 0x32, 0x34, 0xb5,
	0x4e, 0x66, 0x4e, 0x97, 0x4d, 0xc2, 0xde, 0x13, 0xe4, 0xf7, 0xe0, 0xd1, 0x44, 0x8a, 0x4f, 0xc8,
	0x0b, 0x9f, 0x2a, 0x75, 0xf6, 0x45, 0x69, 0x6d, 0xdc, 0x21, 0xd9, 0x79, 0x43, 0x11, 0x36, 0x43,
	0xbf, 0x35, 0x29, 0xbd, 0xf9, 0x87, 0xb0, 0xa5, 0xe5, 0xcd, 0x90, 0xe7, 0x69, 0x50, 0x23, 0xd9,
	0xd5, 0xb4, 0xbc, 0xe9, 0xe5, 0xa9, 0x29, 0xaf, 0x01, 0xeb, 0x04, 0x9a, 0x47, 0x53, 0x20, 0xa5,
	0x99, 0xd4, 0x43, 0x1d, 0xa7, 0x18, 0x34, 0x6c, 0x37, 0x09, 0x19, 0xc4, 0x29, 0xfa, 0x4f, 0xa0,
	0x8e, 0x7c, 0x6c, 0x8d, 0x40, 0xc6, 0x2d, 0xe4, 0x63, 0x32, 0x15, 0x3a, 0x50, 0x66, 0xc7, 0x06,
	0xbb, 0x94, 0x92, 0x74, 0xf0, 0xde, 0x00, 0xfe, 0x09, 0x34, 0xc7, 0xa8, 0x22, 0x19, 0x67, 0x3a,
	0x16, 0x3c, 0xd8, 0xb7, 0x42, 0x2a, 0x41, 0x45, 0xaf, 0xdb, 0xf3, 0x5e, 0xfb, 0x5d, 0xd8, 0x9f,
	0x48, 0xc4, 0xa1, 0x5b, 0x12, 0xa8, 0x87, 0x49, 0x9c, 0xc6, 0x3a, 0x38, 0xa0, 0x93, 0x1f, 0x1b,
	0x1b, 0x15, 0xa2, 0x87, 0xfa, 0xad, 0x31, 0xf8, 0xaf, 0xe1, 0x69, 0x96, 0x8f, 0x92, 0x38, 0x1a,
	0xde, 0x1b, 0x77, 0x48, 0x71, 0x87, 0xd6, 0xe5, 0xcd, 0xc3, 0xa3, 0x73, 0xc5, 0xae, 0x31, 0x08,
	0x96, 0x45, 0x5f, 0x19, 0x73, 0x29, 0x3a, 0x61, 0x1a, 0x95, 0xb6, 0x49, 0x4c, 0x38, 0x55, 0xeb,
	0x49, 0x39, 0xfa, 0x2d, 0x79, 0x98, 0x1c, 0x3d, 0xa4, 0xc2, 0x1e, 0x0d, 0xa0, 0x55, 0x6e, 0xa0,
	0x91, 0x9c, 0x93, 0x80, 0x5b, 0x5f, 0x1e, 0xc5, 0xbb, 0xbe, 0x9e, 0x11, 0xe6, 0x7f, 0x05, 0x4d,
	0xe7, 0x34, 0x66, 0x33, 0xe5, 0x66, 0x0f, 0x2c, 0x74, 0xc9, 0x66, 0x2a, 0xfc, 0xdb, 0x83, 0xe3,
	0x77, 0x4c, 0xea, 0x38, 0x8a, 0x33, 0xe6, 0x96, 0xdd, 0x1a, 0xd2, 0xfe, 0xc2, 0xe2, 0xbf, 0xbd,
	0xc6, 0x2b, 0x8b, 0x6b, 0x7c, 0xd9, 0x0a, 0xfe, 0x09, 0xb6, 0x2f, 0x31, 0x4b, 0xc4, 0x6c, 0x35,
	0x32, 0x07, 0x50, 0xb3, 0x9a, 0x71, 0x44, 0xdc, 0x5b, 0xf8, 0x87, 0x07, 0x6d, 0x53, 0xd1, 0x4f,
	0x78, 0xce, 0x12, 0xc6, 0xa3, 0x15, 0xef, 0xf8, 0x1c, 0xb6, 0x5d, 0x2d, 0x47, 0x36, 0xdc, 0x95,
	0xd3, 0xb5, 0xc1, 0xe5, 0x34, 0x5f, 0xfc, 0xa2, 0xe4, 0xb9, 0x64, 0x24, 0x65, 0xfb, 0xb5, 0x73,
	0xd1, 0x97, 0x0e, 0x0d, 0xbf, 0x87, 0xc3, 0x2b, 0x3e, 0x59, 0x9b, 0x4f, 0xf8, 0x1a, 0xda, 0x45,
	0xfc, 0xea, 0xdf, 0x28, 0x73, 0xfa, 0x87, 0x58, 0x7f, 0x1c, 0x4b, 0x36, 0x5d, 0xeb, 0xf4, 0x7f,
	0x3c, 0xd8, 0xb3, 0xfb, 0x75, 0x8d, 0x0f, 0xe4, 0xc2, 0xa8, 0x6f, 0x2c, 0x1d, 0xf5, 0xca, 0xe7,
	0x51, 0x7f, 0x0a, 0x0d, 0x8e, 0x53, 0x37, 0xa7, 0x56, 0x27, 0x75, 0x8e, 0x53, 0x3b, 0x98, 0xa7,
	0xb0, 0x6b, 0x8c, 0xc5, 0x78, 0x91, 0x4f, 0xd5, 0x56, 0x9d, 0xe3, 0xf4, 0x9d, 0x1d, 0x29, 0x83,
	0x9e, 0x9f, 0xc3, 0x8e, 0x90, 0xd7, 0x1d, 0x3d, 0xff, 0x87, 0xa7, 0xce, 0xeb, 0x05, 0xf9, 0x5f,
	0x9e, 0x5f, 0xc7, 0xfa, 0x63, 0x3e, 0xea, 0x44, 0x22, 0xed, 0x2a, 0xa6, 0xd8, 0x4d, 0x8c, 0xdd,
	0x6b, 0xf1, 0x32, 0x4a, 0x62, 0xe4, 0xfa, 0x25, 0xcb, 0xe2, 0xae, 0xd9, 0x54, 0xa3, 0x1a, 0x05,
	0x7e, 0xfb, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x09, 0x6c, 0x27, 0x73, 0x4c, 0x0a, 0x00, 0x00,
}
