// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: core/contract/common.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResourceCode int32

const (
	ResourceCode_BANDWIDTH  ResourceCode = 0
	ResourceCode_ENERGY     ResourceCode = 1
	ResourceCode_TRON_POWER ResourceCode = 2
)

// Enum value maps for ResourceCode.
var (
	ResourceCode_name = map[int32]string{
		0: "BANDWIDTH",
		1: "ENERGY",
		2: "TRON_POWER",
	}
	ResourceCode_value = map[string]int32{
		"BANDWIDTH":  0,
		"ENERGY":     1,
		"TRON_POWER": 2,
	}
)

func (x ResourceCode) Enum() *ResourceCode {
	p := new(ResourceCode)
	*p = x
	return p
}

func (x ResourceCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceCode) Descriptor() protoreflect.EnumDescriptor {
	return file_core_contract_common_proto_enumTypes[0].Descriptor()
}

func (ResourceCode) Type() protoreflect.EnumType {
	return &file_core_contract_common_proto_enumTypes[0]
}

func (x ResourceCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceCode.Descriptor instead.
func (ResourceCode) EnumDescriptor() ([]byte, []int) {
	return file_core_contract_common_proto_rawDescGZIP(), []int{0}
}

var File_core_contract_common_proto protoreflect.FileDescriptor

const file_core_contract_common_proto_rawDesc = "" +
	"\n" +
	"\x1acore/contract/common.proto\x12\bprotocol*9\n" +
	"\fResourceCode\x12\r\n" +
	"\tBANDWIDTH\x10\x00\x12\n" +
	"\n" +
	"\x06ENERGY\x10\x01\x12\x0e\n" +
	"\n" +
	"TRON_POWER\x10\x02BK\n" +
	"\x18org.tron.protos.contractZ/github.com/fbsobreira/gotron-sdk/pkg/proto/coreb\x06proto3"

var (
	file_core_contract_common_proto_rawDescOnce sync.Once
	file_core_contract_common_proto_rawDescData []byte
)

func file_core_contract_common_proto_rawDescGZIP() []byte {
	file_core_contract_common_proto_rawDescOnce.Do(func() {
		file_core_contract_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_contract_common_proto_rawDesc), len(file_core_contract_common_proto_rawDesc)))
	})
	return file_core_contract_common_proto_rawDescData
}

var file_core_contract_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_core_contract_common_proto_goTypes = []any{
	(ResourceCode)(0), // 0: protocol.ResourceCode
}
var file_core_contract_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_contract_common_proto_init() }
func file_core_contract_common_proto_init() {
	if File_core_contract_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_contract_common_proto_rawDesc), len(file_core_contract_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_contract_common_proto_goTypes,
		DependencyIndexes: file_core_contract_common_proto_depIdxs,
		EnumInfos:         file_core_contract_common_proto_enumTypes,
	}.Build()
	File_core_contract_common_proto = out.File
	file_core_contract_common_proto_goTypes = nil
	file_core_contract_common_proto_depIdxs = nil
}
