// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: core/contract/storage_contract.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BuyStorageBytesContract struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerAddress  []byte                 `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	Bytes         int64                  `protobuf:"varint,2,opt,name=bytes,proto3" json:"bytes,omitempty"` // storage bytes for buy
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyStorageBytesContract) Reset() {
	*x = BuyStorageBytesContract{}
	mi := &file_core_contract_storage_contract_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyStorageBytesContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyStorageBytesContract) ProtoMessage() {}

func (x *BuyStorageBytesContract) ProtoReflect() protoreflect.Message {
	mi := &file_core_contract_storage_contract_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyStorageBytesContract.ProtoReflect.Descriptor instead.
func (*BuyStorageBytesContract) Descriptor() ([]byte, []int) {
	return file_core_contract_storage_contract_proto_rawDescGZIP(), []int{0}
}

func (x *BuyStorageBytesContract) GetOwnerAddress() []byte {
	if x != nil {
		return x.OwnerAddress
	}
	return nil
}

func (x *BuyStorageBytesContract) GetBytes() int64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

type BuyStorageContract struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerAddress  []byte                 `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	Quant         int64                  `protobuf:"varint,2,opt,name=quant,proto3" json:"quant,omitempty"` // trx quantity for buy storage (sun)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyStorageContract) Reset() {
	*x = BuyStorageContract{}
	mi := &file_core_contract_storage_contract_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyStorageContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyStorageContract) ProtoMessage() {}

func (x *BuyStorageContract) ProtoReflect() protoreflect.Message {
	mi := &file_core_contract_storage_contract_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyStorageContract.ProtoReflect.Descriptor instead.
func (*BuyStorageContract) Descriptor() ([]byte, []int) {
	return file_core_contract_storage_contract_proto_rawDescGZIP(), []int{1}
}

func (x *BuyStorageContract) GetOwnerAddress() []byte {
	if x != nil {
		return x.OwnerAddress
	}
	return nil
}

func (x *BuyStorageContract) GetQuant() int64 {
	if x != nil {
		return x.Quant
	}
	return 0
}

type SellStorageContract struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerAddress  []byte                 `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	StorageBytes  int64                  `protobuf:"varint,2,opt,name=storage_bytes,json=storageBytes,proto3" json:"storage_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SellStorageContract) Reset() {
	*x = SellStorageContract{}
	mi := &file_core_contract_storage_contract_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellStorageContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellStorageContract) ProtoMessage() {}

func (x *SellStorageContract) ProtoReflect() protoreflect.Message {
	mi := &file_core_contract_storage_contract_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellStorageContract.ProtoReflect.Descriptor instead.
func (*SellStorageContract) Descriptor() ([]byte, []int) {
	return file_core_contract_storage_contract_proto_rawDescGZIP(), []int{2}
}

func (x *SellStorageContract) GetOwnerAddress() []byte {
	if x != nil {
		return x.OwnerAddress
	}
	return nil
}

func (x *SellStorageContract) GetStorageBytes() int64 {
	if x != nil {
		return x.StorageBytes
	}
	return 0
}

type UpdateBrokerageContract struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerAddress  []byte                 `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	Brokerage     int32                  `protobuf:"varint,2,opt,name=brokerage,proto3" json:"brokerage,omitempty"` // 1 mean 1%
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBrokerageContract) Reset() {
	*x = UpdateBrokerageContract{}
	mi := &file_core_contract_storage_contract_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBrokerageContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBrokerageContract) ProtoMessage() {}

func (x *UpdateBrokerageContract) ProtoReflect() protoreflect.Message {
	mi := &file_core_contract_storage_contract_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBrokerageContract.ProtoReflect.Descriptor instead.
func (*UpdateBrokerageContract) Descriptor() ([]byte, []int) {
	return file_core_contract_storage_contract_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateBrokerageContract) GetOwnerAddress() []byte {
	if x != nil {
		return x.OwnerAddress
	}
	return nil
}

func (x *UpdateBrokerageContract) GetBrokerage() int32 {
	if x != nil {
		return x.Brokerage
	}
	return 0
}

var File_core_contract_storage_contract_proto protoreflect.FileDescriptor

const file_core_contract_storage_contract_proto_rawDesc = "" +
	"\n" +
	"$core/contract/storage_contract.proto\x12\bprotocol\"T\n" +
	"\x17BuyStorageBytesContract\x12#\n" +
	"\rowner_address\x18\x01 \x01(\fR\fownerAddress\x12\x14\n" +
	"\x05bytes\x18\x02 \x01(\x03R\x05bytes\"O\n" +
	"\x12BuyStorageContract\x12#\n" +
	"\rowner_address\x18\x01 \x01(\fR\fownerAddress\x12\x14\n" +
	"\x05quant\x18\x02 \x01(\x03R\x05quant\"_\n" +
	"\x13SellStorageContract\x12#\n" +
	"\rowner_address\x18\x01 \x01(\fR\fownerAddress\x12#\n" +
	"\rstorage_bytes\x18\x02 \x01(\x03R\fstorageBytes\"\\\n" +
	"\x17UpdateBrokerageContract\x12#\n" +
	"\rowner_address\x18\x01 \x01(\fR\fownerAddress\x12\x1c\n" +
	"\tbrokerage\x18\x02 \x01(\x05R\tbrokerageBK\n" +
	"\x18org.tron.protos.contractZ/github.com/fbsobreira/gotron-sdk/pkg/proto/coreb\x06proto3"

var (
	file_core_contract_storage_contract_proto_rawDescOnce sync.Once
	file_core_contract_storage_contract_proto_rawDescData []byte
)

func file_core_contract_storage_contract_proto_rawDescGZIP() []byte {
	file_core_contract_storage_contract_proto_rawDescOnce.Do(func() {
		file_core_contract_storage_contract_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_contract_storage_contract_proto_rawDesc), len(file_core_contract_storage_contract_proto_rawDesc)))
	})
	return file_core_contract_storage_contract_proto_rawDescData
}

var file_core_contract_storage_contract_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_core_contract_storage_contract_proto_goTypes = []any{
	(*BuyStorageBytesContract)(nil), // 0: protocol.BuyStorageBytesContract
	(*BuyStorageContract)(nil),      // 1: protocol.BuyStorageContract
	(*SellStorageContract)(nil),     // 2: protocol.SellStorageContract
	(*UpdateBrokerageContract)(nil), // 3: protocol.UpdateBrokerageContract
}
var file_core_contract_storage_contract_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_contract_storage_contract_proto_init() }
func file_core_contract_storage_contract_proto_init() {
	if File_core_contract_storage_contract_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_contract_storage_contract_proto_rawDesc), len(file_core_contract_storage_contract_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_contract_storage_contract_proto_goTypes,
		DependencyIndexes: file_core_contract_storage_contract_proto_depIdxs,
		MessageInfos:      file_core_contract_storage_contract_proto_msgTypes,
	}.Build()
	File_core_contract_storage_contract_proto = out.File
	file_core_contract_storage_contract_proto_goTypes = nil
	file_core_contract_storage_contract_proto_depIdxs = nil
}
